name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Verify version matches tag
        run: |
          VERSION=$(poetry version -s)
          TAG=${GITHUB_REF#refs/tags/}
          if [ "$VERSION" != "$TAG" ]; then
            echo "Error: Version in pyproject.toml ($VERSION) does not match tag ($TAG)"
            exit 1
          fi
      - name: Build
        run: |
          poetry build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          attestations: false
